/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package v1

import (
	"github.com/spf13/cobra"

	"github.com/hyperledger/fabric-x/tools/fxconfig/internal/cli/v1/cliio"
)

// newTxEndorseCommand creates a command for endorsing transactions.
func newTxEndorseCommand(ctx *CLIContext) *cobra.Command {
	var output outputFlag

	cmd := &cobra.Command{
		Use:   "endorse [file]",
		Short: "Add endorsement signature to transaction",
		Long: `Endorse a transaction with the local MSP's signature.

Each organization that must approve a transaction (per the endorsement policy)
needs to endorse it. This command adds the local organization's signature
to the transaction.

The transaction file must contain both the transaction ID and transaction data
in JSON format (as generated by namespace create/update commands).

If the input transaction is already endorsed, the new endorsement will be
appended to the existing endorsements.

Examples:
  # Endorse transaction and save to new file
  fxconfig tx endorse tx.json --output tx_org1.json

  # Endorse and append to stdout (for piping)
  fxconfig tx endorse tx.json > tx_org1.json

  # Endorse with custom config
  fxconfig tx endorse tx.json --config /path/to/org1-config.yaml --output tx_org1.json`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			input, err := cliio.ResolveInput(cmd, args[0])
			if err != nil {
				return err
			}

			txID, tx, err := ctx.IOTransactionCodec.Decode(input)
			if err != nil {
				return err
			}

			endorsedTx, err := ctx.App.EndorseTransaction(cmd.Context(), txID, tx)
			if err != nil {
				return err
			}

			o, err := ctx.IOTransactionCodec.Encode(txID, endorsedTx)
			if err != nil {
				return err
			}

			return cliio.WriteOutput(cmd, string(output), o)
		},
	}
	output.bind(cmd)

	return cmd
}
