#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
set -euo pipefail

PATH="bin:${PATH}"

runHelp() {
  local command="$1"
  if [[ "$command" == *" help" ]]; then
    $command 2>&1 | sed -E 's/[[:space:]]+$//g'
  else
    $command --help 2>&1 | sed -E 's/[[:space:]]+$//g'
  fi
}

generateHelpText() {
  local DOC="$1"
  local preamble="$2"
  local postscript="$3"
  shift 3

  cat <<EOF2 > "$DOC"
<!---
 File generated by $(basename "$0"). DO NOT EDIT.
 Edit preamble and postscript wrapper files to change generated content.
 --->

EOF2
  cat "$preamble" >> "$DOC"

  local code_delim='```'
  local commands=("$@")
  for x in "${commands[@]}" ; do
    cat <<EOD >> "$DOC"

## $x
$code_delim
$(runHelp "$x")
$code_delim

EOD
  done

  cat "$postscript" >> "$DOC"
  cat docs/wrappers/license_postscript.md >> "$DOC"
}

checkHelpTextCurrent() {
  local doc="$1"
  shift

  local tempfile
  tempfile="$(mktemp -t "$(basename "$doc")".XXXXX)" || exit 1

  generateHelpText "$tempfile" "$@"
  if ! diff -u "$doc" "$tempfile"; then
    rm -f "$tempfile"
    echo "The command line help docs are out of date and need to be regenerated. Run scripts/help_docs.sh generate."
    exit 2
  fi
  rm -f "$tempfile"
}

generateOrCheck() {
  if [[ "$action" == "generate" ]]; then
    generateHelpText "$@"
  elif [[ "$action" == "check" ]]; then
    checkHelpTextCurrent "$@"
  else
    echo "usage: $0 [generate|check]" >&2
    exit 1
  fi
}

action="${1:-generate}"

commands=("configtxgen")
generateOrCheck \
  docs/cli/configtxgen.md \
  docs/wrappers/configtxgen_preamble.md \
  docs/wrappers/configtxgen_postscript.md \
  "${commands[@]}"

commands=("cryptogen help" "cryptogen generate" "cryptogen showtemplate" "cryptogen extend" "cryptogen version")
generateOrCheck \
  docs/cli/cryptogen.md \
  docs/wrappers/cryptogen_preamble.md \
  docs/wrappers/cryptogen_postscript.md \
  "${commands[@]}"

commands=(
  "fxconfig"
  "fxconfig info"
  "fxconfig namespace"
  "fxconfig namespace create"
  "fxconfig namespace list"
  "fxconfig namespace update"
  "fxconfig tx"
  "fxconfig tx endorse"
  "fxconfig tx merge"
  "fxconfig tx submit"
  "fxconfig version"
)
generateOrCheck \
  docs/cli/fxconfig.md \
  docs/wrappers/fxconfig_preamble.md \
  docs/wrappers/fxconfig_postscript.md \
  "${commands[@]}"
